# Generated by Django 4.2.1 on 2023-05-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNUmber',
            new_name='phoneNumber',
        ),
    ]
